version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my_postgres_container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "12000:5432"
    volumes:
      - ./migrations/init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql

#  app:
#    container_name: my_app
#    build:
#      dockerfile: Dockerfile
#    ports:
#      - "11000:11000"
##      - "12000:12000"
#    depends_on:
#      - postgres
