version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "12000:5432"
    volumes:
      - ./migrations/init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql

  app:
#    network_mode: host
    container_name: nsi
    build:
      dockerfile: Dockerfile
    ports:
      - "11000:11000"
#      - "12000:12000"
    depends_on:
      - postgres
