CREATE TABLE telescope_system (
    id SERIAL PRIMARY KEY,
    telescope VARCHAR(50),
    aperture_params VARCHAR(50),
    diameter NUMERIC,
    effective_radiation_waist_factor NUMERIC,
    magnification_system VARCHAR(50),
    magnification NUMERIC,
    inversion BOOLEAN,
    gimbal VARCHAR(50),
    system_state VARCHAR(50),
    x_vector NUMERIC[],
    target_internal_state NUMERIC[],
    sigma_state_noise NUMERIC,
    constant_system_params VARCHAR(50),
    J1 NUMERIC,
    J2 NUMERIC,
    J3 NUMERIC,
    J4 NUMERIC,
    Kg NUMERIC,
    Fs NUMERIC,
    pid_coefs1 NUMERIC[],
    pid_coefs2 NUMERIC[],
    control_vector NUMERIC[],
    real_fsm VARCHAR(50),
    state_fsm VARCHAR(50),
    x_vector_fsm NUMERIC[],
    target_internal_state_fsm NUMERIC[],
    sigma_fsm NUMERIC,
    state_limits NUMERIC[],
    params_fsm VARCHAR(50),
    control_vector_fsm NUMERIC[],
    omega01 NUMERIC[],
    Q1 NUMERIC[],
    Q2 NUMERIC[],
    pid_coefs1_fsm NUMERIC[],
    pid_coefs2_fsm NUMERIC[],
    linear_angle_detector VARCHAR(50),
    ideal_lens VARCHAR(50),
    distance_to_photodetector NUMERIC,
    matrix_photodetector VARCHAR(50),
    pixel_size NUMERIC[],
    resolution NUMERIC[],
    responsivity NUMERIC,
    uniform_spot VARCHAR(50),
    radius NUMERIC
);

INSERT INTO telescope_system (
    telescope, aperture_params, diameter, effective_radiation_waist_factor, magnification_system, magnification,
    inversion, gimbal, system_state, x_vector, target_internal_state, sigma_state_noise, constant_system_params,
    J1, J2, J3, J4, Kg, Fs, pid_coefs1, pid_coefs2, control_vector, real_fsm, state_fsm, x_vector_fsm,
    target_internal_state_fsm, sigma_fsm, state_limits, params_fsm, control_vector_fsm, omega01, Q1, Q2,
    pid_coefs1_fsm, pid_coefs2_fsm, linear_angle_detector, ideal_lens, distance_to_photodetector, matrix_photodetector,
    pixel_size, resolution, responsivity, uniform_spot, radius
) VALUES (
    'telescope', 'aperture', 0.025, 1, 'magnificationSystem', 10,
    FALSE, 'gimbal', 'systemState', ARRAY[0, 0, 0, 0], ARRAY[0, 0], 0, 'constantSystemParams',
    5.72, 5.79, 7.04, 6.22, 9.8, 0, ARRAY[3550, 0, 2550], ARRAY[1500, 0, 920], ARRAY[0, 0], 'RealFSM', 'stateFSM',
    ARRAY[0, 0, 0, 0], ARRAY[0, 0], 0, ARRAY[0.0436332, 0.0436332], 'paramsFSM', ARRAY[0, 0], ARRAY[859, 862],
    ARRAY[53], ARRAY[55], ARRAY[1.41796884671, 0, 0.000369883624321], ARRAY[1.41735102407, 0, 0.000368509825954],
    'LinearAngleDetector', 'IdealLens', 0.07, 'MatrixPhotodetector', ARRAY[20.16e-6, 20.16e-6], ARRAY[128.0, 128.0],
    1, 'UniformSpot', 0.00125
);
